### ISSUE TITLE
ERROR(S)

### ISSUE THREAD

**Issue by calmsand22** [rdavisau/sg-unpack#4]
When i'm trying to run .exe program from command promt it appear some errors like that dont detect the mpk file. Sorry i'm not good at some coding or else
Here's the look https://ibb.co/G5DB70L

**Comment by rdavisau** [comment]
Hello,

Because your input/output paths contain spaces, I think you should quote them (`"`). So like this:

`sg-unpack -i "D:\Goovery\G\Steins Gate it self's an English book\USRDIR" -f .ogg -o "D:\Goovery\G\Steins Gate it self's an English book\USRDIR\input files" -q true`

The filter in your command will extract only `.ogg` files, which I think will be all music, dialogue and sound effects.

**Comment by rdavisau** [comment]
Actually, I checked and it should be ok to provide paths without quotes. 
The problem in your screenshot was that the `-i` was written backwards (`i-`) 🙂 .

**Comment by calmsand22** [comment]
Yes! I think i had mess it up, your program working fast and smooth. Aw bunch of thanks :)

**Comment by rdavisau** [comment]
No problems! Glad it is all working 👍
